//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_id { get; set; }
        public string Student_name { get; set; }
        public int Age { get; set; }
        public string Blood_group { get; set; }
        public string Father_s_Name { get; set; }
        public string Mother_s_Name { get; set; }
        public int Grade { get; set; }
        public Nullable<int> Subject_Id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
